name: Makefile CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - run: git fetch --prune --unshallow

      # - name: Install dependencies (ubuntu)
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install wx3.0-headers libwxgtk3.0-gtk3-0v5 libwxgtk3.0-gtk3-dev

      # - name: Install dependencies (macos)
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     brew install wxwidgets@3.0
      #     ln -s /usr/local/bin/wx-config-3.0 /usr/local/bin/wx-config

      # - name: Install dependencies (windows)
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     choco install wxwidgets

      - name: Build binaries
        run: make bossac
